### ISSUE TITLE
Couldn't find data files

### ISSUE THREAD

**Issue by jat9292** [spoilt333/onco-aae#1]
Hello, please could you upload or at least put a link to find the 2 needed data files in order to run the code?
i.e '/data/dumps/shuf.train.txt' and '/data/dumps/bitfpt.test.txt'
Thanks in advance.

**Comment by spoilt333** [comment]
Hi! I can't put it here, because I used private datasets, so you should collect your own data.

**Comment by jat9292** [comment]
Ok thanks, but I don't understand yet the code. 
Could you tell me please what kind of data are expected to be in train and test?

**Comment by spoilt333** [comment]
Sure. You should provide dataset with 166-bit fingerprints (MACCS) from rdkit. lines in both train and test files looks like this:
`CC(C)[C@@H]([C@H](c1ccccc1I)OC)OC(=NC1CC2CCC1C2)O	0000000000000000000000100010000000000000000000000000000000000000000000010100010000000010001010010000000011100110000011100010010110001100001010011110110100011111111110
`

**Comment by gaojunhui68** [comment]
Could you describe the file 'unique_data_file_name' for me? Are there 6252 lines in this file? I want to know detail information of this file. Thanks

**Comment by sweetkurapika** [comment]
.npy files are binary files, but @spoilt333  said : 
_lines in both train and test files looks like this:
CC(C)[C@@H]([C@H](c1ccccc1I)OC)OC(=NC1CC2CCC1C2)O 0000000000000000000000100010000000000000000000000000000000000000000000010100010000000010001010010000000011100110000011100010010110001100001010011110110100011111111110_

I think this makes it confusing for us, I wrote the following code for converting smiles to MACCS and save them according to what @spoilt333  said:

```
from rdkit import Chem
from rdkit.Chem import MACCSkeys
def createMACCS(input_smi_file,output_maccs_file):
    suppl = Chem.SmilesMolSupplier(input_smi_file)      # Read the smiles_file
    mols  = [Chem.MolFromSmiles(Chem.MolToSmiles(x)) for x in suppl]        # Create Molecules
    fps   = [MACCSkeys.GenMACCSKeys(x) for x in mols]   # MACCS Keys

    file = open(output_maccs_file,"w")
    for i in range(len(mols)):
        tostr = Chem.MolToSmiles(mols[i]) + '\n'
        for j in range(len(fps[i])):
            tostr += str(fps[i][j])
        file.write(tostr+'\n')
```
But once it came to loading the data using get_input_data, the compiler complained saying:
` Failed to interpret file 'data/mcf7.data.npy' as a pickle`
That's obvious, because the data were saved in a text format.
I hope @spoilt333 can at least provide us with how to save the data in case his private dataset can't be published.

**Comment by KuzmaKhrabrov** [comment]
We had quite a peculiar input format when we wrote that code. It was something like this:
array([ '0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000001000000011000010101000010011110',
       '0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000001000000000000001001010011110',
       '0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010100000100001001100001100000001001010011110',
       ...,
       '0010000000000000001000000000000000000000000100000001000000000000100010000010111100001100010001000101000011000000000001111101000110000000110001001011001010010101111010',
       '0010000010000000000000000000000000000000001100010000110000000000000010000000101000100000111001011000110111000011000011011001011111100001101101100111001000010110101110',
       '0010001000000000000000000000000000000000000100010000000000000000000010000000000000000000100000000000010001000001000000000001010001100001001100000101000000000010000100'], 
      dtype='|S166')
saved to text file with numpy.save

**Comment by sweetkurapika** [comment]
Thanks @KuzmaKhrabrov , I succeeded in creating the input file and this is the function that I used:

```
def createMACCS(input_file,output_maccs_file):
    # Generating 166 public MACCS keys for each molecule
    # suppl = Chem.SDMolSupplier(input_file)                                # Read the sdf_file
    suppl = Chem.SmilesMolSupplier(input_file)                              # Read the smiles_file
    mols  = [Chem.MolFromSmiles(Chem.MolToSmiles(x)) for x in suppl]            # Create Molecules
    fps   = [MACCSkeys.GenMACCSKeys(x) for x in mols]                           # MACCS Keys
    np.save(output_maccs_file,fps)

```
I also have the same question of @gaojunhui68 , I hope you describe how can we prepare the unique_data_file of 6252 . You mentioned in the code this comment:
`# there is 6252 unique fingerprints and multiple experiments with each`
But still we cant understand what you mean.

I appreciate your help

**Comment by gaojunhui68** [comment]
@KuzmaKhrabrov，would  you describe how can we prepare the unique_data_file of 6252 .How many columns are there in this file? What's the data for each column? 

I appreciate your help.
