### ISSUE TITLE
StopIteration issue

### ISSUE THREAD

**Issue by jat9292** [spoilt333/onco-aae#2]
Hi, I get an error while trying to run the vae.ipynb code which I am unable to solve: 

<_io.TextIOWrapper name='./fpt.vae.log' mode='w' encoding='cp1256'> epoch #1
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
<ipython-input-80-a15f769f5611> in <module>()
      1 with open('./fpt.vae.log', 'w') as log:
----> 2     hist1 = vae.train(log)

<ipython-input-78-8d560292f6a0> in train(self, log)
    126             else:
    127                 saver.save(sess, './fpt.vae.%de.model.ckpt' % e)
--> 128                 test_x = test_gen.__next__()
    129                 loss = sess.run(self.ae_loss, feed_dict={self.input_x: test_x})
    130                 print(log, "ae_loss: %f" % loss)

StopIteration: 

Notice that I adapted the code by changing .next() to .__next__() because I have been using python 3 instead of python 2 (tensorflow is not compatible with python2 on windows).

Thanks in advance.

**Comment by spoilt333** [comment]
I'm not sure about what is your question about.
